name: Train Model

on:
  workflow_dispatch:
    inputs:
      train:
        description: "Perform model training"
        required: true

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Data
        run: python prepare_data.py

      - name: Train Model
        run: python train_model.py --dataset ${{ github.event.inputs.train }}

      - name: Evaluate Model
        run: python evaluate_model.py

  archive_model:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Archive Model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: model.h5
