name: Train and Archive Model

on:
  workflow_dispatch:
    inputs:
      train:
        description: "Train the model"
        required: true

jobs:
  prepare_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare data
        run: python prepare_data.py

  train:
    needs: prepare_data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Train model
        run: python train_model.py

  archive:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Archive model file
        run: |
          mkdir -p artifacts
          cp model.h5 artifacts/
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: artifacts/
